before_script:
  - echo '\n' > /root/mysql_root_password
language: python
python:
  - "2.7"
install:
  - "deactivate"
  - "pip install virtualenv"
  - "python deploy/bootstrap.py"
  - "python deploy/tasks.py deploy:dev -n"
# command to run tests, e.g. python setup.py test
script:
  - "python django/website/manage.py test"
