language: python
python:
  - "2.7"
install:
  - "deactivate"
  - "pip install virtualenv"
  - "python deploy/bootstrap.py"
# command to run tests, e.g. python setup.py test
script:
  - "python deploy/tasks.py run_tests"
